OpenDataPlane/odp-docker-images

- x86_64/Dockerfile
Signed-off-by: Dmitry Eremin-Solenikov <dmitry.ereminsolenikov@linaro.org>
Workaround-for: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907365
> x86_64: add libibverbs-dev to fix mlx4/mlx5 linking

- ubuntu_18.04/Dockerfile
Latest Ubuntu DPDK package is missing some required libraries (e.g.
crypto), so DPDK has to be built manually from sources.
> ubuntu_18.04: build dpdk library from sources

- ubuntu_20.04-x86_64/Dockerfile
Fixes linking (GCC 9.2) getting stuck in Travis when building ODP with DPDK
pktio.
> ubuntu_20.04: build dpdk manually

- ubuntu_18.04-x86_64/Dockerfile
Curl is required by Codecov coverage test.
> ubuntu_18.04: add curl

- ubuntu_20.04-arm64/Dockerfile
- ubuntu_20.04-x86_64/Dockerfile
Add missing iostream dependency.
> ubuntu_20.04: fix clang build

- centos_8-x86_64/Dockerfile
DPDK build requires cmp tool which is provided by diffutils package.
> centos_8: add diffutils dependency

- .github/workflows/ci-pipeline.yml
Add GitHub Actions workflow for building and pushing container images.
Images are pushed to the GitHub Container Registry service. To push
built images CONTAINER_REGISTRY_USER and CONTAINER_REGISTRY_TOKEN GitHub
repository secrets have to be set.
> github_actions: add workflow for building and pushing container images

- centos_7-x86_64/Dockerfile
- ubuntu_18.04-arm64/Dockerfile
- ubuntu_18.04-armhf/Dockerfile
- ubuntu_18.04-i386/Dockerfile
- ubuntu_18.04-ppc64el/Dockerfile
- ubuntu_18.04-x86_64-dpdk_18.11/Dockerfile
- ubuntu_18.04-x86_64-dpdk_19.11/Dockerfile
- ubuntu_18.04-x86_64/Dockerfile
- ubuntu_20.04-arm64/Dockerfile
- ubuntu_20.04-riscv64/Dockerfile
- ubuntu_20.04-x86_64/Dockerfile
```
Add libcli-dev (or libcli-devel), used by ODP CLI helper, to all
images currently in use.
Signed-off-by: Jere Leppänen <jere.leppanen@nokia.com>
```
> add libcli

- centos_7-x86_64/Dockerfile
CU_add_suite_with_setup_and_teardown() function required by the ODP CI is
not available in the CentOS 7 CUnit package. Install the latest CUnit
version from source.
> centos_7: install cunit from source

- .github/workflows/ci-pipeline.yml
- ubuntu_20.04-x86_64-coverity-linux-generic/Dockerfile
Since Coverity is a static analysis tool, it doesn't require a multitude
of different builds to be analyzed, so add just one job.
Add a Dockerfile with only the necessary packages for a non-DPDK build
and the ability to download Coverity.
Signed-off-by: Juraj Linkeš <juraj.linkes@pantheon.tech>
> github_actions: add Coverity job and Dockerfile

- .github/workflows/ci-pipeline.yml
- centos_8-arm64-native/Dockerfile
- ubuntu_16.04-arm64-native/Dockerfile
- ubuntu_18.04-arm64-native-dpdk_18.11/Dockerfile
- ubuntu_18.04-arm64-native/Dockerfile
- ubuntu_20.04-arm64-native/Dockerfile
- Updating CI to build on Graviton2 self hosted runners
- Adding Dockerfiles for Ubuntu and CentOS
Jobs have been restricticted to only run when repo is owned by the
OpenDataPlane organisation. This is to prevent the CI triggering on
forks of the project where Graviton2 self-hosted runners are not
available.
> Adding support for Arm64 containers

- centos_8-arm64-native/Dockerfile
- ubuntu_16.04-arm64-native/Dockerfile
- ubuntu_18.04-arm64-native-dpdk_18.11/Dockerfile
- ubuntu_18.04-arm64-native/Dockerfile
- ubuntu_20.04-arm64-native-dpdk_20.11/Dockerfile
- ubuntu_20.04-arm64-native/Dockerfile
Use of the OPT=big compiler flag when building the AArch64cryptolib
results in stack smashing errors for the native CI jobs for Armv8 crypto.
This flag can be removed and AArch64cryptolib can detect the CPU
implementation during the build.
Signed-off-by: Malvika Gupta <Malvika.Gupta@arm.com>
> remove OPT compiler flag for AArch64cryptolib

- rocky_linux_8-arm64-native/Dockerfile
- rocky_linux_8-x86_64/Dockerfile
Install procps package, which includes sysctl tool required by ODP-DPDK CI.
> rocky_8: install procps package

- .github/workflows/ci-pipeline.yml
- ubuntu_22.04-openssl-arm64-native/Dockerfile
- ubuntu_22.04-openssl-x86_64/Dockerfile
DPDK OpenSSL PMD has currently compatibility issues with OpenSSL 3.0, so
install OpenSSL 1.1.1 manually.
> ubuntu_22.04: add containers with manually built openssl

- ubuntu_20.04-arm64-native-dpdk_19.11/Dockerfile
Package required for DPDK 19.11 test.
> ubuntu_20.04: add build-essential package

- ubuntu_22.04-arm64-native/Dockerfile
- ubuntu_22.04-x86_64/Dockerfile
Add GCC 13 to Ubuntu 22.04 images.
> ubuntu_22.04: add gcc-13 packages

- rocky_linux_8-arm64-native/Dockerfile
- rocky_linux_9-arm64-native/Dockerfile
- ubuntu_18.04-arm64-native/Dockerfile
- ubuntu_20.04-arm64-native-dpdk_20.11/Dockerfile
- ubuntu_20.04-arm64-native-dpdk_21.11/Dockerfile
- ubuntu_20.04-arm64-native-dpdk_22.11/Dockerfile
- ubuntu_20.04-arm64-native/Dockerfile
- ubuntu_22.04-arm64-native/Dockerfile
- ubuntu_23.04-arm64-native/Dockerfile
Generic platform DPDK option adds '-moutline-atomics' flag, which breaks ODP CI clang build jobs.
> dpdk: remove generic platform option from aarch64

- ubuntu_22.04-arm64-native/Dockerfile
- ubuntu_22.04-x86_64/Dockerfile
For machine learning support, install ONNX Runtime library (https://github.com/microsoft/onnxruntime), and onnx and numpy python packages.
> ubuntu_22.04: install ML dependencies

- ubuntu_20.04-arm64-graviton3/Dockerfile
Clang 12 includes support for Neoverse V1 CPU.
> ubuntu_20.04: replace default clang on graviton3

- .github/workflows/ci-pipeline.yml
Update GitHub hosted runners from Ubuntu 20.04 to 22.04.
> github_ci: update github hosted runners

- ubuntu_24.04-arm64-graviton3/Dockerfile
As part of this [PR](https://github.com/OpenDataPlane/odp/pull/2209) to the odp repository, it seems some required dependencies were missing from the graviton3 ubuntu 24.04 container used for CI.
This PR aims to address these issues
> graviton3: ubuntu 24.04: install missing dependencies

- rocky_linux_8-arm64-graviton3/Dockerfile
- rocky_linux_8-arm64-native/Dockerfile
- rocky_linux_8-x86_64/Dockerfile
Fix '__atomic_exchange_16 is not available' configure error in ODP CI.
> rocky_8: fix ODP CI clang build
